services:
  autoware:
    build:
      context: ./docker
      dockerfile: Dockerfile
    user: "${USER_ID}:${GROUP_ID}"
    command: ["bash", "-c", "python3 -m streamlit run ./ws/src/app.py --server.port 8080 --server.runOnSave true"]
    tty: true
    working_dir: "/home/autoware/"
    volumes:
      - ./src:/home/autoware/ws/src
    ports:
      - "8080:8080"